name: Build Windows x64 Release
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # 新增：安装libpng依赖，解决png.h缺失
      - name: Install libpng via Chocolatey
        run: choco install libpng --no-progress -y

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            10.0.x
          dotnet-quality: 'preview'

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      - name: Restore NuGet packages
        run: |
          nuget restore MapleHaSuite.sln
          dotnet restore MapleHaSuite.sln

      - name: Build Release x64
        run: msbuild MapleHaSuite.sln /p:Configuration=Release /p:Platform="x64" /p:RestorePackages=false

      - name: Zip Compiled Binaries
        run: Compress-Archive -Path ./HaRepacker/bin/x64/Release/* -DestinationPath Harepacker-x64.zip

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Harepacker-x64
          path: Harepacker-x64.zip
